version: "3.8"

networks:
    network_envisia:
        driver: bridge

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        container_name: envisia-nginx
        ports:
            - "8040:80"
        restart: unless-stopped
        volumes:
            - ./public:/var/www/html/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        networks:
            - network_envisia

    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: envisia-app
        volumes:
            - ./:/var/www/html
        restart: unless-stopped
        tty: true
        networks:
            - network_envisia
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: envisia-mysql
        ports:
            - "3340:3306"
        volumes:
            - ./.data/mysql:/var/lib/mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: envisia
            MYSQL_USER: envisia
            MYSQL_PASSWORD: envisia
            MYSQL_ROOT_PASSWORD: envisiapass
        networks:
            - network_envisia
